services:
  front:
    build: ./front
    environment:
      - WDS_SOCKET_PORT=0
    restart: always
    volumes:
      - ./front/src:/app/src
      - node_modules:/app/node_modules
    ports:
      - 3001:3000
  api:
    build: ./back
    restart: always
    volumes:
      - ./back/src:/app/src
      - node_modules:/app/node_modules
    ports:
      - 5001:5000
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: changemeinprodplease
      POSTGRES_DB: mydb

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
