services:
  front:
    build: ./front
    environment:
      - WDS_SOCKET_PORT=0
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    restart: always
    volumes:
      - ./front/src:/app/src
    ports:
      - 3000:3000

  api:
    build: ./back
    restart: always
    volumes:
      - ./back/src:/app/src
    ports:
      - 5000:5000
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: changemeinprodplease
      POSTGRES_DB: mydb

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
